#!/usr/bin/env bash

# we're using nix, so bail
#return

# added by Anaconda2 2018.12 installer
function enableConda()
{
    local isHere=$(fnexists conda)
    local base="${HOME}/anaconda/anaconda3"
    if [ "x$isHere" == "x" ]
    then
        # >>> conda initialize >>>
        # !! Contents within this block are managed by 'conda init' !!
        __conda_setup="$("${base}/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
        if [ $? -eq 0 ]; then
            eval "$__conda_setup"
        else
            if [ -f "${base}/etc/profile.d/conda.sh" ]; then
                . "${base}/etc/profile.d/conda.sh"
            else
                export PATH="${base}/bin:$PATH"
            fi
        fi
        unset __conda_setup
        # <<< conda initialize <<<
    fi
}
