#!/usr/bin/env bash

if [ "x" = "x$(type -t docker)" ]
then
    return
fi

# npm ()
# {
#     docker run \
#         -it --rm \
#         --net=host \
#         --user=${UID}:${GID} \
#         -v $(pwd):/source \
#         --entrypoint npm \
#         moli/node $*
# }
#
# node ()
# {
#     docker run \
#         -it --rm \
#         --net=host \
#         --user=${UID}:${GID} \
#         -v $(pwd):/source \
#         moli/node $*
# }
#
# gatsby ()
# {
#     docker run \
#         -it \
#         --rm \
#         --net=host \
#         --user=${UID}:${GID} \
#         -v $(pwd):/usr/src/app \
#         moli/gatsby $*
# }
#
# slack()
# {
#     xhost local:root
#     docker run --rm -it \
#         -v /etc/localtime:/etc/localtime:ro \
#         -v /tmp/.X11-unix:/tmp/.X11-unix \
#         -e DISPLAY=unix$DISPLAY \
#         --device /dev/snd \
#         --device /dev/dri \
#         --device /dev/video0 \
#         --group-add audio \
#         --group-add video \
#         -v "${HOME}/.slack:/root/.config/Slack" \
#         -v "${HOME}/.slack/downloads:/root/Downloads" \
#         --ipc="host" \
#         --name slack \
#         moli/slack "$@"
# }
#
# htop()
# {
#     docker run --rm -it --pid host jess/htop
# }


#formatter()
#{
#    docker run --rm -it \
#        -v $(pwd):/source \
#        -u $UID:$GID \
#        clang-format $*
#}

#bazel()
#{
#    docker run --rm \
#        -v $(pwd):/usr/src/app \
#        -it bazel2 bazel $*
#}

#rebuild()
#{
#    docker run --rm \
#        -it -v "$(pwd)":/usr/src/app \
#        -e _UID=$UID \
#        -e _GID=$GID \
#        toolchain \
#        $*
#}

dockerpython3()
{
    docker run -it --rm --name python-3-script \
        -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp python:3.7-rc-slim python $*
}

#pip3()
#{
#    docker run -it --rm --name python-3-script \
#        -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp python:3.7-rc-slim pip3 $*
#}

#virtualenv3()
#{
#    docker run -it --rm --name python-3-script \
#        -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp python:3.7-rc-slim python -m venv $*
#}

graphviz()
{
    docker run -it --rm --name dot \
        -v "$(pwd)":/scratch -w /scratch -u $UID:$GID moli/alpine $*
}

drill()
{
    docker run -it --rm --name drill \
        -v "$(pwd)":/scratch -w /scratch -u $UID:$GID \
        moli/alpine drill $*
}

#keepassxc()
#{
#    docker run -d -v /tmp/.X11-unix:/tmp/.X11-unix \
#        -v /etc/machine-id:/etc/machine-id:ro \
#        -v /usr/share/X11/xkb:/usr/share/X11/xkb/:ro \
#        -v $HOME/.config/keepassxc:/root/.config/keepassxc \
#        -e DISPLAY=unix$DISPLAY \
#        keepassxc
#}

dockercmake()
{
    docker run -it -e HOME=/home/anon -e USER=anon -u $UID:$GID \
        -v $(pwd):/usr/src/app -w /usr/src/app \
        --entrypoint cmake build-tools $*
}

svn()
{
    docker run -it -e HOME=/home/anon -e USER=anon -u $UID:$GID \
        -v $(pwd):/usr/src/app -w /usr/src/app \
        --entrypoint svn build-tools $*
}

dockerImagesClean()
{
    HASHES=$(docker images | grep '<none>' | awk '{print $3}')
    if test "x${HASHES}x" != "xx"
    then
        for h in "${HASHES}"
        do
            docker rmi $h
        done
    fi
}

dockerPsClean()
{
    HASHES=$(docker ps -a -q -f "status=exited" | awk '{print $1}')
    if test "x${HASHES}x" != "xx"
    then
        for h in "${HASHES}"
        do
            docker stop $h
            docker rm $h
        done
    fi
}

function solc()
{
    docker run -it --rm \
        -v $(pwd):/solidity \
        -v $DOCKER_USER_HOME_DIR:/usr/src/home \
        -e HOME=/usr/src/home \
        ethereum/solc:stable $*
}

#dockerpython()
#{
#    docker run -it --rm \
#        -e USER=anon -e HOME=/home/anon -v ~/.docker/home:/home/anon -u $UID:$GID \
#        --entrypoint /bin/bash python:2.7.15-slim-stretch $*
#}

find_venv()
{
    local exe=${1:-bpython}
    local path=$(type -P $exe)

    # look in the current path
    if [ "x$path" = "x" ]
    then

        # look in the venv3 path
        local venvpath="${HOME}/venv3/bin/${exe}"
        path=$(type -P $venvpath)

        if [ "x$path" = "x" ]
        then

            # look in the venv path
            venvpath="${HOME}/venv/bin/${exe}"
            path=$(type -P $venvpath)

            if [ "x$path" = "x" ]
            then
                echo ""
            else
                echo $path
            fi
        else
            echo $path
        fi

    else
        echo $path
    fi
}

bpython()
{
    local path=$(find_venv bpython)

    if [ "x$path" = "x" ]
    then
        docker run -it --rm \
            -e USER -e HOME -u $UID:$GID \
            --entrypoint bpython python3
    else
        exec $path $*
    fi
}

#R()
#{
#    docker run -it --rm \
#        -v ~/.docker/home:/home/anon -e _UID=$UID -e _GID=$UID \
#        -e R_HISTFILE=/home/anon/.RHistory \
#        rproject $*
#}

#nodered()
#{
#    docker run -it --rm --name mynodered \
#        -p 1880:1880 \
#        -e FLOWS=/data/flows/flows.json \
#        -v ~/.docker/home/node-red:/data/flows \
#        moli/nodered
#}

dockerState()
{
    local name=$1
    local state
    state=$(docker inspect --format "{{.State.Running}}" "$name" 2>/dev/null)

    echo "$state"
}

stopIfRunning()
{
    local name=$1
    local state
    state=$(dockerState "$name")

    if [[ "$state" == "true" ]]
    then
        docker stop "$name"
        docker rm "$name"
    elif [[ "x$state"  != "x" ]]
    then
        docker rm "$name"
    fi

}

startJenkins()
{
    local LOCAL_PORT=${1:-49000}
    local name=jenkins

    stopIfRunning $name

    docker run -u root \
        --rm \
        -d \
        -p ${LOCAL_PORT}:8080 \
        -p 50000:50000 \
        -e JENKINS_OPTS="--prefix=/jenkins" \
        -v /opt/docker/jenkinsci:/var/jenkins_home \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --name $name \
        jenkinsci/blueocean
}

startPihole()
{
    local IP=$(ifconfig en0 | grep 'inet\>' | awk '{ print $2 }')
    local IP_ADDRESS=${1:-$IP}
    local name=pihole
    stopIfRunning $name

    docker run -d --name $name \
        -e ServerIP=$IP_ADDRESS \
        -e TZ=New_York \
        -e WEBPASSWORD='no ads' \
        -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 \
        -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 \
        -v ~/pihole/:/etc/pihole/ \
        --dns=127.0.0.1 --dns=1.1.1.1 \
        --cap-add=NET_ADMIN \
        --restart=unless-stopped \
        pihole/pihole:latest
}

sdr()
{
    docker run -ti \
        --device=/dev/bus/usb \
        sdr-base "$*"
}
rtl_433()
{
    docker run -ti \
        --device=/dev/bus/usb \
        --entrypoint=/usr/bin/rtl_433 \
        sdr "$*"
}

_jekky()
{
    local USER_UID=$(id -u)
    docker run --rm \
           --user "$(id -u)":"$(id -g)" \
           -p 4000:4000 \
           -e USER \
           -e GEM_HOME=/srv/jekyll/.gem \
           --volume="$PWD:/srv/jekyll" -it \
           jekky "$@"
}

mkpasswd()
{
    docker run -i busybox mkpasswd $*
}

bundle()
{
    _jekky bundle "$@"
}

jekyll()
{
    _jekky "jekyll $@"
}

php()
{
    local USER_UID=$(id -u)
    docker run --rm \
           --user "$(id -u)":"$(id -g)" \
           -p 4000:4000 \
           -e USER \
           --volume="$PWD:/app" -it \
           phpcli php "$@"
}

arc()
{
    local USER_UID=$(id -u)
    docker run --rm \
           --user "$(id -u)":"$(id -g)" \
           -p 4000:4000 \
           -e USER \
           --volume="$HOME/git/arcanist/bin:/app" -it \
           arcanist "$@"
}

#pavucontrol()
#{
#    local USER_UID=$(id -u)
#
#    docker run -ti \
#        -v=/run/user/${USER_UID}/pulse:/run/user/1000/pulse \
#        --mount type=bind,source=/dev/shm,target=/dev/shm \
#        -e DISPLAY \
#        -v=/tmp/.X11-unix:/tmp/.X11-unix \
#        -e NO_AT_BRIDGE=1 \
#        pulsey pavucontrol ${@}
#}

#cargo()
#{
#    echo "[$*]"
#    docker run -it --rm --name cargo \
#        --user "$(id -u)":"$(id -g)" \
#        -e USER \
#        -v "$PWD":/usr/src/myapp -w /usr/src/myapp \
#        cargo:latest $*
#}

nmap()
{
    docker run -it --rm --name nmappy \
        --user "$(id -u)":"$(id -g)" \
        -e USER \
        nmap $*
}

function workdir() {
    typeset count=$(wc -l ~/.workdir | awk '{ print $1 }' 2>/dev/null)
    typeset options=$(cat ~/.workdir 2>/dev/null)

    if [[ $count = 1 ]] ; then
        echo "only one option: going to $options"
        chdir $options
    else
        typeset choice=$(echo $options | gum choose | cut -d: -f1)

        if [[ -n $choice ]] ; then
            chdir "$choice"
        fi
    fi
}


