#!/usr/bin/env bash

if [ "xLinux" = "x$(uname)" ]
then
    alias web='x-www-browser'


    function enableJava()
    {
        JDK_VERSION="13.0.2"
        GROOVY_VERSION="3.0.1"
        JAVA_HOME="/usr/local/java/jdk-${JDK_VERSION}"
        export GROOVY_HOME="/usr/local/java/groovy-${GROOVY_VERSION}"
        PATH="${JAVA_HOME}/bin:${GROOVY_HOME}/bin:$PATH"

        export JDK_VERSION
        export JAVA_HOME

        function disableJava()
        {

            unset GROOVY_VERSION
            unset GROOVY_HOME
            unset JDK_VERSION
            unset JAVA_HOME
            # remove the java paths
            PATH=$(stripFromPath "${JAVA_HOME}/bin")
            PATH=$(stripFromPath "${GROOVY_HOME}/bin")

        }

        unset enableJava
    }

    function enableEclipse()
    {
        enableJava
        ECLIPSE_VERSION="java-2019-12"
        ECLIPSE_HOME="${HOME}/eclipse/${ECLIPSE_VERSION}/eclipse/"
        PATH="${ECLIPSE_HOME}:$PATH"

        export ECLIPSE_VERSION
        export ECLIPSE_HOME

        function disableEclipse()
        {

            unset ECLIPSE_VERSION
            unset ECLIPSE_HOME
            # remove the java paths
            PATH=$(stripFromPath "${ECLIPSE_HOME}")

        }

        unset enableEclipse
    }
fi
