
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"

alias ls=eza
alias ll='ls -larh -snew'

if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin"
fi

alias vim=nvim
alias vi=nvim

bindkey -e

# use go 1.23.2
eval "$(gvm 1.23.2)"
export GOPATH=$HOME/sandbox/golang/
export PATH=$PATH:${GOPATH}/bin

alias ep='elastic-package'
alias epb='elastic-package build'
alias epc='elastic-package check'
alias epr='elastic-package stack up -vvd --services package-registry'

# functions
function root() {
    local root_dir=$(find-root)

    if [ -n ${root_dir} ] ; then
        echo "Found root dir at ${root_dir}"
        cd "${root_dir}"
    else
        echo "Could not find a root from here ($(pwd))"
    fi
}

function nvm()
{

    typeset nvmdir="${HOME}/.config/nvm"
    if [ -d "${nvmdir}" ]
    then
        export NVM_DIR="${nvmdir}"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

        # invoke the real nvm function
        nvm "$@"
    else
        echo "nvm is not installed" >&2
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
    fi
}
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mo/.local/src/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mo/.local/src/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mo/.local/src/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mo/.local/src/google-cloud-sdk/completion.zsh.inc'; fi

export EDITOR=nvim

export XDG_CONFIG_HOME=$HOME/.config/

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/mo/.cache/lm-studio/bin"
