
if [[ -d /opt/homebrew/bin ]] ; ; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
eval "$(starship init zsh)"

alias ls=eza
alias ll='ls -larh -snew'

if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin"
fi

alias vim=nvim
alias vi=nvim

bindkey -e

# use go 1.23.2
if [[ -n "$(command -v gvm 2>/dev/null)" ]] ; then
    eval "$(gvm 1.23.2)"
    export GOPATH=$HOME/sandbox/golang/
    export PATH=$PATH:${GOPATH}/bin
fi

alias ep='elastic-package'
alias epb='elastic-package build'
alias epc='elastic-package check'
alias epr='elastic-package stack up -vvd --services package-registry'

# functions
function root() {
    local root_dir=$(find-root)

    if [ -n ${root_dir} ] ; then
        echo "Found root dir at ${root_dir}"
        cd "${root_dir}"
    else
        echo "Could not find a root from here ($(pwd))"
    fi
}

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mo/.local/src/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mo/.local/src/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mo/.local/src/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mo/.local/src/google-cloud-sdk/completion.zsh.inc'; fi

export EDITOR=nvim

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/mo/.cache/lm-studio/bin"
