
setopt inc_append_history

eval "$(starship init zsh)"

alias ls=eza
alias l='ls -larh -snew'
alias ll='ls -larh -snew'

if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin"
fi
function appendUnique() {
    if [[ ":$PATH:" != *":$1:"* ]]
    then
        # only append if the directory exists
        if [ -d "$1" ]
        then
            PATH="$PATH:$1"
        fi
    fi
}

# used on linux
appendUnique /opt/nvim/bin
appendUnique /opt/rust/bin

alias vim=nvim
alias vi=nvim

bindkey -e

# use go 1.24.2
if [[ -n "$(command -v gvm)" ]] ; then
    eval "$(gvm 1.24.2)"
    export GOPATH=$HOME/sandbox/golang/
    export PATH=$PATH:${GOPATH}/bin
fi

# functions
function root() {
    local root_dir=$(find-root)

    if [ -n ${root_dir} ] ; then
        echo "Found root dir at ${root_dir}"
        cd "${root_dir}"
    else
        echo "Could not find a root from here ($(pwd))"
    fi
}

function tsa() {
    typeset options=$(tmux ls 2>/dev/null)
    typeset count=$(echo $options | wc -l)
    typeset all_options=$(echo "add a new session: unnamed\n$options")
    typeset choice=$(echo $all_options | gum choose | cut -d: -f1)

    if [[ $choice = "add a new session" ]] ; then
        typeset name=$(gum input)
        if [[ -n $name ]] ; then
            tmux new -s $name
        fi
    elif [[ -n $choice ]] ; then
        tmux attach -t $choice
    fi
}

function serve() {
    python3 -m http.server $*
}

export EDITOR=nvim

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/mo/.cache/lm-studio/bin"

# function npx() {
#     node npx "$@"
# }
# 
# function npm() {
#     node npm "$@"
# }
# 
# function node() {
#     docker run -it --rm --net=host -e USER=node -u $(id -u):$(id -g) -v ./:/app -v $HOME/.npm:/home/node/.npm -w /app node:latest "$@"
# }

alias wd=workdir
function workdir() {
    typeset request=${1:-}
    typeset options=$(cat ~/.workdir 2>/dev/null)

    typeset choice=$(echo $options | gum filter --select-if-one --value "${request}"| cut -d: -f1)

    if [[ -n $choice ]] ; then
        # make sure to get rid of comments
        typeset d=$(echo $choice | cut -d'#' -f1)
        chdir "$d"
    fi
}

if type brew &>/dev/null; then
    fpath=($(brew --prefix)/share/zsh-completions $fpath)
fi

if [[ -d $HOME/.asdf ]] ; then
    export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
    fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
fi

if type zoxide > /dev/null ; then
    eval "$(zoxide init zsh)"
fi

if [[ -d $HOME/.local/bin ]] ; then
    export PATH="$PATH:$HOME/.local/bin"
fi

if [[ -d $HOME/.bun ]] ; then
    export PATH="$HOME/.bun/bin:$PATH"
fi
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/mo/.docker/completions $fpath)
autoload -Uz compinit && compinit
# End of Docker CLI completions


# for uv
. "$HOME/.local/bin/env"

if [[ -d $HOME/perl5 ]] ; then
    PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
    PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
    PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
    PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT;
    PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;
fi

# for perforce
export P4PORT=p4proxy-sc:4101
