
#alias google-chrome="/opt/google/google-chrome --ppapi-flash-path=/opt/google/chrome*/PepperFlash/libpepflashplayer.so --ppapi-flash-version=$PEPPER_FLASH_VERSION"
#
export TMUX=`which tmux`
alias tmux='${TMUX} -2 -S ~/.tmux.sock'

alias count="awk 'BEGIN{}{x += \$1}END{ print x }'"

if [ "Darwin" = $(uname) ]
then
    alias ls="$(which ls) -F -G"
else
    alias ls="$(which ls) -F --color=auto"
fi

if [ "Linux" = "$(uname)" ]
then
    alias setclip="xclip -selection c"
    alias getclip="xclip -selection c -o"

    alias ep="elastic-package"
    alias epb="elastic-package build"
    alias epp="elastic-package test pipeline"
    alias epc="elastic-package check"
    alias epr="elastic-package stack up -vvvd --services package-registry"

    function elastic-package() {
        # if elastic-package is not a file, enableGo
        local path=$(type -P elastic-package)
        if [ -z "${path}" ] ; then
            enableGo
            path=$(type -P elastic-package)
        fi

        if [ -n "${path}" ] ; then
            # now unset myself
            unset -f elastic-package

            # and finally call elastic-package
            elastic-package $@
        else
            echo "Could not find elastic-package, even with 'enableGo'"
        fi
    }

    export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0"
fi

