#!/bin/bash

#complete -d cd

COMPLETION_DIR=$HOME/.bash_completion.d/
if [ -d "${COMPLETION_DIR}" ]
then
    for f in $(command ls -1 "${COMPLETION_DIR}")
    do
        . ${COMPLETION_DIR}/$f
    done
fi

