
#alias google-chrome="/opt/google/google-chrome --ppapi-flash-path=/opt/google/chrome*/PepperFlash/libpepflashplayer.so --ppapi-flash-version=$PEPPER_FLASH_VERSION"
#
export TMUX=`which tmux`
alias tmux='${TMUX} -2 -S ~/.tmux.sock'

if [ "Darwin" = $(uname) ]
then
    alias ls="$(which ls) -F -G"
else
    alias ls="`which ls` -F --color=auto"
fi

if [ "Linux" = "$(uname)" ]
then
    alias setclip="xclip -selection c"
    alias getclip="xclip -selection c -o"
fi
